### ISSUE TITLE
Detect candlestick patterns

### ISSUE THREAD

**Issue by thanhnguyennguyen** [thanhnguyennguyen/trading-indicator#35]
Detect below candlestick patterns:

- [x] Abandoned Baby.
- [x] Bearish Engulfing Pattern.
- [x] Bullish Engulfiing Pattern.
- [x] Dark Cloud Cover.
- [x] Downside Tasuki Gap.
- [x] Doji.
- [x] DragonFly Doji.
- [x] GraveStone Doji.
- [x] BullishHarami.
- [x] Bearish Harami Cross.
- [x] Bullish Harami Cross.
- [x] Bullish Marubozu.
- [x] Bearish Marubozu.
- [x] Evening Doji Star.
- [x] Evening Star.
- [x] Bearish Harami.
- [x] Piercing Line.
- [x] Bullish Spinning Top.
- [x] Bearish Spinning Top.
- [x] Morning Doji Star.
- [x] Morning Star.
- [x] Three Black Crows.
- [x] Three White Soldiers.
- [x] Bullish Hammer.
- [x] Bearish Hammer.
- [x] Bullish Inverted Hammer.
- [x] Bearish Inverted Hammer.
- [x] Hammer Pattern.
- [ ] Hammer Pattern (Unconfirmed).
- [x] Hanging Man.
- [ ] Hanging Man (Unconfirmed).
- [x] Shooting Star.
- [ ] Shooting Star (Unconfirmed).
- [x] Tweezer Top.
- [x] Tweezer Bottom.

(This content is created via [Gittool](https://github.com/thanhnguyennguyen/lazy/tree/master/git)) 
 On behalf of [thanhnguyennguyen](https://github.com/thanhnguyennguyen)

**Comment by JamesonBR** [comment]
Any update for this issue?

**Comment by CalvinLarano** [comment]
Any update on this ?

**Comment by thanhnguyennguyen** [comment]
we are busy.
Anyone feel interested can create Pull request for them

**Comment by thanhnguyennguyen** [comment]
plan for next release
